# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
   group: 'credentials'
   acrName: 'techlab01saacrhelloworld'  # Replace with your Azure Container Registry name
   dockerHubImage: 'sujayabu/myhelloworldimage:v1'  # Replace with your Docker Hub image details
   acrImage: '$(acrName).azurecr.io/myhelloworldimage:v1'  # Replace <your-image-name> and <tag>
   azureSubscriptionEndpoint: 'LabTech01SVCHW'
   containerRegistryName: 'techlab01saacrhelloworld.azurecr.io'

steps:
# Step 1: Log in to Azure using Azure CLI and set up networking rules
# Log in to Azure Container Registry (ACR)
- task: AzureCLI@2
  displayName: 'Add Agent IP to allowed networks in ACR'
  inputs:
    azureSubscription: 'LabTech01SVCHW'  # Azure service connection name
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $publicip = (Invoke-WebRequest -Uri "http://ifconfig.me/ip").Content
      az acr network-rule add --name $(containerRegistryName) --ip-address $publicip
      
# Step 2: Log in to Azure Container Registry (ACR) using Docker login
- task: AzureCLI@2
  displayName: 'Log in to Azure Container Registry (ACR)'
  inputs:
    azureSubscription: 'LabTech01SVCHW'  # Azure service connection name
    scriptType: 'pscore'  # Using PowerShell Core
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $(containerRegistryName)

# Step 3: Pull the Docker image from Docker Hub
- script: |
    echo "Pulling image from Docker Hub..."
    docker pull $(dockerHubImage)
  displayName: 'Pull Image from Docker Hub'
  
# Step 4: Tag the image for ACR
- script: |
    echo "Tagging image for ACR..."
    docker tag $(dockerHubImage) $(acrImage)
  displayName: 'Tag Image for ACR'
  
# Step 5: Push the image to ACR
- script: |
    echo "Pushing image to ACR..."
    docker push $(acrImage) || exit 1
  displayName: 'Push image to ACR'
