# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
   group: 'credentials'
   acrName: 'techlab01saacrhelloworld'  # Replace with your Azure Container Registry name
   dockerHubImage: 'sujayabu/myhelloworldimage:v1'  # Replace with your Docker Hub image details
   acrImage: '$(acrName).azurecr.io/myhelloworldimage:v1'  # Replace <your-image-name> and <tag>
   azureSubscriptionEndpoint: 'LabTech01SVCHW'
   containerRegistryName: 'techlab01saacrhelloworld.azurecr.io'

steps:
# Log in to Docker Hub (if required)
#- task: Docker@2
#  displayName: 'Login to Docker Hub'
#  inputs:
#    containerRegistry: '<dockerhub-service-connection>'  # Create a service connection for Docker Hub if your image is private

# Log in to Azure Container Registry (ACR)
- task: AzureCLI@2
  inputs:
    azureSubscription: 'LabTech01SVCHW'  # Azure service connection name
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $publicip = (Invoke-WebRequest -Uri "http://ifconfig.me/ip").Content
      az acr network-rule add --name $(containerRegistryName) --ip-address $publicip

- task: AzureCLI@2
  displayName: 'Log in to Azure Container Registry (ACR)'
  inputs:
    azureSubscription: 'LabTech01SVCHW'  # Azure service connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
     echo $(acrPassword) | docker login $(acrName).azurecr.io --username $(acrUsername) --password-stdin
     echo "Logging into Azure Container Registry..."

# Pull the Docker image from Docker Hub
- script: |
    echo "Pulling image from Docker Hub..."
    docker pull $(dockerHubImage)
  displayName: 'Pull Image from Docker Hub'
  
# Tag the image for ACR
- script: |
    echo "Tagging image for ACR..."
    docker tag $(dockerHubImage) $(acrImage)
  displayName: 'Tag Image for ACR'
  
# Push the image to ACR
- script: |
    echo "Pushing image to ACR..."
    docker push $(acrImage) || exit 1
  displayName: 'Push Image to ACR'
